export const ProjectsList = [
  {
    id: "portfolio-website",
    title: "Portfolio Website",
    type: "main-project",
    image: "/portfolio.webp",
    alt: "Portfolio text on a pc",
    description: "Personal portfolio built with React.",
    tags: ["React", "CSS", "JavaScript"],
    github: "https://github.com/Cynthilizy/myPortfolio",
    live: "my-portfolio-seven-pink-82.vercel.app",
    demoType: "none",
  },

  {
    id: "rock-paper-scissors",
    title: "Rock Paper Scissors",
    type: "mini-game",
    image: "/rock-paper-scissors.jpg",
    alt: "Hands in the shape of Rock Paper Scissors",
    description: "Rock Paper Scissors game",
    tags: ["React", "CSS", "JavaScript"],
    github:
      "https://github.com/Cynthilizy/mini-games/tree/main/src/rock-paper-scissors",
    live: "https://mini-games-orpin-nu.vercel.app/",
    demoType: "web",
  },

  {
    id: "calibration-workflow",
    title: "Calibration Workflow",
    type: "case-study",
    image: "/introScreen.png",
    alt: "Calibration WorkFlow Image",
    description: "AWS-connected robotic calibration dashboard.",
    tags: ["React", "JavaScrip", "AWS", "IoT", "Robotics", "System Design"],
    github: "https://github.com/Cynthilizy/calibration_workflow",
    live: "https://youtu.be/cJCTL3LuTKU",
    demoType: "video",
  },

  {
    id: "snake-master",
    title: "Snake Master",
    type: "mini-game",
    image: "/snake.jpg",
    alt: "A cartoon snake",
    description: "Snake grows as long as player can survive",
    tags: ["React", "CSS", "JavaScript"],
    github:
      "https://github.com/Cynthilizy/mini-games/tree/main/src/snake-master",
    live: "https://mini-games-orpin-nu.vercel.app/",
    demoType: "web",
  },

  {
    id: "robotic-automation",
    title: "Robotic Automation",
    type: "case-study",
    image: "/robot.jpg",
    alt: "Photo of Meca500 robot",
    description: "Robot Control as part of a calibration process.",
    tags: ["Python"],
    github: "https://github.com/Cynthilizy/Robotic_Automation_Process",
    live: "",
    demoType: "none",
  },

  {
    id: "guess-the-capital",
    title: "Guess The Capital",
    type: "mini-game",
    image: "/capitals.jpg",
    alt: "Image showing world flags",
    description: "Quiz game to guess capitals of the world",
    tags: ["React", "CSS", "JavaScript"],
    github:
      "https://github.com/Cynthilizy/mini-games/tree/main/src/capitals-quiz",
    live: "https://mini-games-orpin-nu.vercel.app/",
    demoType: "web",
  },

  {
    id: "guess-the-flag",
    title: "Guess The Flag",
    type: "mini-game",
    image: "/flag.jpeg",
    alt: "Image showing world flags",
    description: "Quiz game to guess the flags of the world",
    tags: ["React", "CSS", "JavaScript"],
    github: "https://github.com/Cynthilizy/mini-games/tree/main/src/flag-quiz",
    live: "https://mini-games-orpin-nu.vercel.app/",
    demoType: "web",
  },
];
